services:
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net # only backend can reach it
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  backend:
    image: vedant27/esports-backend:latest # ← pull from Docker Hub (was: build: ./server)
    deploy:
        replicas: 3               # ← run THREE copies of the backend
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/esports-arena
    networks:
      - frontend-net # so nginx can reach it
      - backend-net # so it can reach mongo
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy   # ← wait until Mongo PASSES its healthcheck
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data        # persists certs across restarts (avoids rate limits)
      - caddy_config:/config
    networks:
        - frontend-net            # same network as frontend, so it can reach it by name
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    image: vedant27/esports-frontend:latest # ← pull from Docker Hub (was: build: ./client)
    ports:
      - "8080:80"
    networks:
      - frontend-net # NOT on backend-net → can't reach mongo
    depends_on:
      - backend
    restart: unless-stopped

networks:
  frontend-net:
  backend-net:

volumes:
  mongo-data:
  caddy_data:
  caddy_config:
